'use client'
import { useEffect, useMemo, useState } from 'react'
import { Bot, ChevronDown, Code2, Globe2, Menu, Plus, Search, Send, Settings, Sparkles, Trash2, X } from 'lucide-react'

type Mode='chat'|'thinking'|'research'|'code'; type Provider='mistral'|'groq'|'cerebras'|'openai'|'openrouter'
type Msg={role:'user'|'assistant';content:string;mode?:Mode;provider?:Provider}
const providers:Record<Provider,{name:string;models:string[]}>={mistral:{name:'Mistral',models:['mistral-large-latest','mistral-small-latest']},groq:{name:'Groq',models:['llama-3.3-70b-versatile','openai/gpt-oss-120b']},cerebras:{name:'Cerebras',models:['llama-3.3-70b','qwen-3-235b-a22b-instruct-2507']},openai:{name:'OpenAI',models:['gpt-5','gpt-4.1-mini']},openrouter:{name:'OpenRouter',models:['openai/gpt-5','anthropic/claude-sonnet-4']}}
const starters=[['Explain quantum computing simply',''],['Build a React dashboard','code'],['Research the latest AI news','research'],['Help me think through a decision','thinking']]
export default function Home(){
 const [messages,setMessages]=useState<Msg[]>([]),[input,setInput]=useState(''),[mode,setMode]=useState<Mode>('chat'),[provider,setProvider]=useState<Provider>('groq'),[model,setModel]=useState(providers.groq.models[0]),[loading,setLoading]=useState(false),[sidebar,setSidebar]=useState(true),[settings,setSettings]=useState(false),[keys,setKeys]=useState<Record<string,string>>({})
 useEffect(()=>{const saved=localStorage.getItem('lumina-messages');if(saved)setMessages(JSON.parse(saved));const k=localStorage.getItem('lumina-provider');if(k){const x=JSON.parse(k);setProvider(x.provider);setModel(x.model)}},[])
 useEffect(()=>localStorage.setItem('lumina-messages',JSON.stringify(messages)),[messages])
 const modes=useMemo(()=>[{id:'chat' as Mode,label:'Chat',icon:Sparkles},{id:'thinking' as Mode,label:'Thinking',icon:Bot},{id:'research' as Mode,label:'Research',icon:Globe2},{id:'code' as Mode,label:'Code',icon:Code2}],[])
 async function send(text=input){if(!text.trim()||loading)return;const user:Msg={role:'user',content:text,mode};setMessages(m=>[...m,user]);setInput('');setLoading(true);try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:[...messages,user],mode,provider,model})});const data=await r.json();setMessages(m=>[...m,{role:'assistant',content:data.content||data.error||'Something went wrong.',mode,provider}])}catch{setMessages(m=>[...m,{role:'assistant',content:'Connection failed. Check your provider API key in Settings.',mode}])}finally{setLoading(false)}}
 function changeProvider(p:Provider){setProvider(p);setModel(providers[p].models[0]);localStorage.setItem('lumina-provider',JSON.stringify({provider:p,model:providers[p].models[0]}))}
 return <main className="h-screen flex overflow-hidden bg-white">
  {sidebar&&<aside className="w-[270px] shrink-0 border-r border-neutral-200 bg-[#fafafa] flex flex-col"><div className="p-4 flex items-center gap-2"><div className="w-9 h-9 rounded-xl bg-neutral-950 text-white grid place-items-center"><Sparkles size={18}/></div><div><b>Lumina</b><div className="text-[11px] text-neutral-500">AI workspace</div></div></div><button onClick={()=>{setMessages([]);localStorage.removeItem('lumina-messages')}} className="mx-3 mt-2 flex items-center gap-2 rounded-xl border border-neutral-200 bg-white px-3 py-2.5 text-sm font-medium hover:bg-neutral-50"><Plus size={16}/> New chat</button><div className="px-3 pt-6 text-[11px] font-semibold text-neutral-400 uppercase tracking-wider">Workspace</div><div className="p-2 space-y-1">{['Today','Recent chats','Saved'].map((x,i)=><button key={x} className="w-full text-left px-3 py-2 rounded-lg text-sm text-neutral-600 hover:bg-neutral-100">{i===0?'Today':x}</button>)}</div><div className="mt-auto p-3"><button onClick={()=>setSettings(true)} className="w-full flex items-center gap-2 rounded-xl px-3 py-2.5 text-sm hover:bg-neutral-100"><Settings size={16}/> Settings</button><div className="mt-2 p-3 rounded-xl bg-white border border-neutral-200 text-xs text-neutral-500">Private by design<br/><span className="text-neutral-800 font-medium">Keys stay server-side.</span></div></div></aside>}
  <section className="flex-1 flex flex-col min-w-0"><header className="h-16 border-b border-neutral-200 flex items-center justify-between px-4 md:px-6 glass"><div className="flex items-center gap-3"><button className="p-2 hover:bg-neutral-100 rounded-lg" onClick={()=>setSidebar(!sidebar)}>{sidebar?<X size={18}/>:<Menu size={18}/>}</button><div className="hidden sm:flex items-center gap-2 text-sm"><span className="font-semibold">Lumina AI</span><span className="text-neutral-400">/</span><span className="text-neutral-500">{modes.find(x=>x.id===mode)?.label}</span></div></div><div className="flex items-center gap-2"><div className="relative"><select value={provider} onChange={e=>changeProvider(e.target.value as Provider)} className="appearance-none border border-neutral-200 rounded-xl pl-3 pr-8 py-2 text-xs bg-white outline-none">{Object.entries(providers).map(([k,v])=><option key={k} value={k}>{v.name}</option>)}</select><ChevronDown size={13} className="absolute right-2 top-2.5 pointer-events-none text-neutral-500"/></div><div className="relative hidden md:block"><select value={model} onChange={e=>{setModel(e.target.value);localStorage.setItem('lumina-provider',JSON.stringify({provider,model:e.target.value}))}} className="appearance-none border border-neutral-200 rounded-xl pl-3 pr-8 py-2 text-xs bg-white outline-none">{providers[provider].models.map(m=><option key={m}>{m}</option>)}</select><ChevronDown size={13} className="absolute right-2 top-2.5 pointer-events-none text-neutral-500"/></div><button onClick={()=>setSettings(true)} className="p-2 rounded-xl hover:bg-neutral-100"><Settings size={17}/></button></div></header>
   <div className="flex-1 overflow-y-auto scrollbar"><div className="max-w-4xl mx-auto px-4 md:px-8 py-10">{messages.length===0?<div className="min-h-[62vh] grid place-items-center"><div className="w-full max-w-2xl"><div className="text-center mb-10"><div className="mx-auto mb-5 w-14 h-14 rounded-2xl bg-neutral-950 text-white grid place-items-center shadow-lg"><Sparkles size={25}/></div><h1 className="text-4xl md:text-5xl font-semibold tracking-tight">What can I help you create?</h1><p className="mt-3 text-neutral-500">One workspace for chat, reasoning, research and code.</p></div><div className="grid sm:grid-cols-2 gap-3">{starters.map(([t,m])=><button key={t} onClick={()=>{if(m)setMode(m as Mode);send(t)}} className="text-left p-4 rounded-2xl border border-neutral-200 hover:border-neutral-400 hover:shadow-sm transition"><div className="text-sm font-medium">{t}</div><div className="text-xs text-neutral-400 mt-1">{m||'chat'}</div></button>)}</div></div></div>:<div className="space-y-7">{messages.map((m,i)=><div key={i} className={`animate-in ${m.role==='user'?'flex justify-end':'flex gap-3'}`}>{m.role==='assistant'&&<div className="w-8 h-8 rounded-lg bg-neutral-950 text-white grid place-items-center shrink-0"><Sparkles size={14}/></div>}<div className={m.role==='user'?'max-w-[80%] bg-neutral-950 text-white rounded-2xl rounded-br-md px-4 py-3 text-sm':'max-w-[90%] prose-lite text-[15px]'}>{m.role==='assistant'&&<div className="text-[10px] uppercase tracking-wider text-neutral-400 mb-2">{m.provider?providers[m.provider].name:''} · {m.mode}</div>}<div className="whitespace-pre-wrap">{m.content}</div></div></div>)}{loading&&<div className="flex gap-3"><div className="w-8 h-8 rounded-lg bg-neutral-950 text-white grid place-items-center"><Sparkles size={14}/></div><div className="flex gap-1 items-center h-8"><span className="dot animate-pulse"/><span className="dot animate-pulse"/><span className="dot animate-pulse"/></div></div>}</div>}</div></div>
   <div className="border-t border-neutral-200 p-3 md:p-5 bg-white"><div className="max-w-4xl mx-auto"><div className="flex gap-2 mb-2 overflow-x-auto">{modes.map(({id,label,icon:Icon})=><button key={id} onClick={()=>setMode(id)} className={`shrink-0 flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs ${mode===id?'bg-neutral-950 text-white':'bg-neutral-100 text-neutral-600'}`}><Icon size={13}/>{label}</button>)}</div><div className="border border-neutral-300 rounded-2xl p-2 flex items-end gap-2 shadow-sm focus-within:border-neutral-600"><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder={`Message Lumina in ${mode} mode…`} rows={1} className="flex-1 resize-none outline-none px-2 py-2.5 text-sm max-h-40"/><button onClick={()=>send()} disabled={loading||!input.trim()} className="w-10 h-10 rounded-xl bg-neutral-950 text-white grid place-items-center disabled:opacity-30"><Send size={17}/></button></div><div className="text-[10px] text-neutral-400 text-center mt-2">Lumina can make mistakes. Verify important information.</div></div></div>
  </section>
  {settings&&<div className="fixed inset-0 z-50 bg-black/20 flex justify-end" onClick={()=>setSettings(false)}><div onClick={e=>e.stopPropagation()} className="w-full max-w-md h-full bg-white border-l border-neutral-200 p-6 overflow-y-auto"><div className="flex justify-between items-center"><div><h2 className="text-xl font-semibold">Settings</h2><p className="text-sm text-neutral-500">Connect your own AI providers.</p></div><button onClick={()=>setSettings(false)}><X/></button></div><div className="mt-8 space-y-5">{Object.entries(providers).map(([k,v])=><div key={k} className="border border-neutral-200 rounded-2xl p-4"><div className="font-medium text-sm">{v.name}</div><input type="password" placeholder={`${v.name} API key`} value={keys[k]||''} onChange={e=>setKeys({...keys,[k]:e.target.value})} className="mt-3 w-full border border-neutral-200 rounded-xl px-3 py-2 text-sm outline-none focus:border-neutral-500"/><p className="text-[11px] text-neutral-400 mt-2">Encrypted server-side in an HttpOnly cookie. Never committed to source control.</p></div>)}<button onClick={async()=>{await fetch('/api/keys',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(keys)});setKeys({});setSettings(false)}} className="w-full bg-neutral-950 text-white rounded-xl py-3 text-sm font-medium">Save securely</button><button onClick={()=>{localStorage.clear();location.reload()}} className="w-full border border-red-200 text-red-600 rounded-xl py-3 text-sm flex items-center justify-center gap-2"><Trash2 size={15}/> Clear local data</button></div></div></div>}
 </main>}
